public class login extends javax.swing.JFrame {
Conexion con=new Conexion();
Connection cn=con.conectar();

public static  frmregistro fr;

public login() {
initComponents();
setLocationRelativeTo(null);
}

private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

/**
* Creates new form login
*/


/**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.
*/
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {

passContraseña = new javax.swing.JPanel();
txtUsuario = new javax.swing.JTextField();
txtusuario = new javax.swing.JLabel();
txtpassword = new javax.swing.JLabel();
jPasswordField1 = new javax.swing.JPasswordField();
btnIniciar = new javax.swing.JButton();
btnregistrar = new javax.swing.JButton();
btnSalir = new javax.swing.JButton();
jLabel1 = new javax.swing.JLabel();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

passContraseña.setBackground(new java.awt.Color(0, 255, 204));

txtUsuario.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txtUsuarioActionPerformed(evt);
}
});

txtusuario.setText("Usuario:");

txtpassword.setText("contraseña:");

jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jPasswordField1ActionPerformed(evt);
}
});

btnIniciar.setText("Iniciar");
btnIniciar.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnIniciarActionPerformed(evt);
}
});

btnregistrar.setText("Registrar");
btnregistrar.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnregistrarActionPerformed(evt);
}
});

btnSalir.setText("salir");
btnSalir.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnSalirActionPerformed(evt);
}
});

jLabel1.setText("jLabel1");

javax.swing.GroupLayout passContraseñaLayout = new javax.swing.GroupLayout(passContraseña);
passContraseña.setLayout(passContraseñaLayout);
passContraseñaLayout.setHorizontalGroup(
passContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(passContraseñaLayout.createSequentialGroup()
.addGap(25, 25, 25)
.addGroup(passContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(btnIniciar)
.addGroup(passContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGroup(passContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(passContraseñaLayout.createSequentialGroup()
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
.addComponent(btnregistrar)
.addGap(56, 56, 56)
.addComponent(btnSalir)
.addGap(39, 39, 39))
.addGroup(passContraseñaLayout.createSequentialGroup()
.addGap(26, 26, 26)
.addGroup(passContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
);
passContraseñaLayout.setVerticalGroup(
passContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(passContraseñaLayout.createSequentialGroup()
.addGap(22, 22, 22)
.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(18, 18, 18)
.addGroup(passContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(txtusuario)
.addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(30, 30, 30)
.addGroup(passContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(txtpassword)
.addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(passContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(btnIniciar)
.addComponent(btnregistrar)
.addComponent(btnSalir))
.addContainerGap(97, Short.MAX_VALUE))
);

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(passContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(passContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
);

pack();
}// </editor-fold>

private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {
String usuario=txtusuario.getText();
String pass=txtpassword.getText();

if(!usuario.equals("")||!pass.equals("")){
try {
PreparedStatement ps=cn.prepareStatement("SELECT tipo_nivel FROM usuarios WHERE email='"+usuario+"' AND clave='"+pass+"'");
ResultSet rs=ps.executeQuery();
if(rs.next()){

String tiponivel=rs.getString("tipo_nivel");
if(tiponivel.equalsIgnoreCase("GESTOR")){
dispose();
panel_usuario_gestor pg=new panel_usuario_gestor();
pg.setVisible(true);
}else if(tiponivel.equalsIgnoreCase("COMERCIAL")){
dispose();
PANEL_USUARIO_cOMERCIAL pc=new PANEL_USUARIO_cOMERCIAL();
pc.setVisible(true);
}
}else{
JOptionPane.showMessageDialog(null, "USUARIO O CONTRASEÑA INCORRECTOS");

}
} catch (Exception e) {
JOptionPane.showMessageDialog(null, "ERROR AL INICIAR SESION"+e);

}
}else{
JOptionPane.showMessageDialog(null, "DEBE COMPLETAR LOS CAMPOS");

}


// TODO add your handling code here:
}

private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {
frm_registro registro = new frm_registro();
registro.setAlwaysOnTop(true);//rl formulario de registro aparece siempre encima del formulario de login.
registro.setLocationRelativeTo(this);// centrar o justificar la pisición del formulario
registro.setVisible(true); // permite que se vea el formulario
registro.toFront();//trae al frente el formulario frm_registro
// TODO add your handling code here:
}

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {
btnSalir.addActionListener(e -> System.exit(0));
int opcion = JOptionPane.showConfirmDialog(
null,
"¿Deseas salir del programa?",
"Confirmar salida",
JOptionPane.YES_OPTION);
if (opcion == JOptionPane.YES_OPTION) {
System.exit(0);
}

// TODO add your handling code here:
}

/**
* @param args the command line arguments
*/
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
if ("Nimbus".equals(info.getName())) {
javax.swing.UIManager.setLookAndFeel(info.getClassName());
break;
}
}
} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
logger.log(java.util.logging.Level.SEVERE, null, ex);
}
//</editor-fold>

/* Create and display the form */
java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
}

// Variables declaration - do not modify
private javax.swing.JButton btnIniciar;
private javax.swing.JButton btnSalir;
private javax.swing.JButton btnregistrar;
private javax.swing.JLabel jLabel1;
private javax.swing.JPasswordField jPasswordField1;
private javax.swing.JPanel passContraseña;
private javax.swing.JTextField txtUsuario;
private javax.swing.JLabel txtpassword;
private javax.swing.JLabel txtusuario;
// End of variables declaration
}

PANEL UUARIO GESTOR
package formularios;

/**
*
* @author nj554
*/